# ********************************************
# 各レシピにおける設定
# ********************************************
vim:
  user: vagrant
  home: /home/vagrant
tmux:
  version: 2.1
  user: vagrant
  home: /home/vagrant
anyenv:
  install_versions:
    - rbenv:
      - 2.3.1
